/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 art.gltf --transform 
Files: art.gltf [56MB] > art-transformed.glb [744.28KB] (99%)
Author: Matthew Collings (https://sketchfab.com/mtcollings)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/victorian-framed-painting-pbr-game-ready-b2895c1c3b42401a949deac049e0051d
Title: Victorian Framed Painting - PBR Game Ready
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/art-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Victorian_Framed_Painting_Victorian_Paintings_0.geometry} material={materials.Victorian_Paintings} position={[-1.717, -0.871, -0.033]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/art-transformed.glb')
